# Generated by Django 3.1.7 on 2021-03-08 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
