# Generated by Django 3.1.7 on 2021-03-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField(default=0, unique=True)),
                ('bookName', models.CharField(default=0, max_length=50, null=True)),
                ('numberOfBook', models.IntegerField(null=True)),
                ('bookAuthor', models.CharField(default=0, max_length=70, null=True)),
                ('bookPublication', models.CharField(default=0, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('processId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bookId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book'),
        ),
    ]
