# Generated by Django 3.1.7 on 2021-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210313_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_delivery',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_taken',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
