# Generated by Django 3.1.7 on 2021-03-18 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210318_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rentId', models.IntegerField(primary_key=True, serialize=False)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('bookId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookId',
        ),
        migrations.AddField(
            model_name='rent',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.user'),
        ),
    ]
